# Generated by Django 5.1.2 on 2024-11-05 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name_plural": "Autores",
            },
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                (
                    "capa",
                    models.ImageField(
                        blank=True,
                        default="capa/default.jpg",
                        null=True,
                        upload_to="capa/",
                    ),
                ),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("n_paginas", models.IntegerField()),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.autor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("pagina_final", models.IntegerField(default=0)),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.livro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto_perfil", models.ImageField(blank=True, null=True, upload_to="")),
                ("descricao", models.TextField(blank=True)),
                ("moderador", models.BooleanField(default=False)),
                ("id_username", models.CharField(max_length=30, unique=True)),
                (
                    "seguidores",
                    models.ManyToManyField(
                        blank=True, related_name="seguidores_de", to="mainapp.usuario"
                    ),
                ),
                (
                    "seguindo",
                    models.ManyToManyField(
                        blank=True, related_name="seguidos_por", to="mainapp.usuario"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
            },
        ),
        migrations.CreateModel(
            name="Curtida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comentario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.comentario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comentario",
            name="leitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainapp.usuario"
            ),
        ),
        migrations.CreateModel(
            name="Resenha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("texto", models.TextField()),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.livro"
                    ),
                ),
                (
                    "leitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.usuario",
                    ),
                ),
            ],
            options={
                "unique_together": {("livro", "leitor")},
            },
        ),
        migrations.CreateModel(
            name="Interage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("QL", "Quero Ler"), ("LN", "Lendo"), ("LD", "Lido")],
                        max_length=2,
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.livro"
                    ),
                ),
                (
                    "leitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Interações",
                "unique_together": {("livro", "leitor")},
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("nota", models.IntegerField()),
                ("conteudo", models.TextField()),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.livro"
                    ),
                ),
                (
                    "leitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "unique_together": {("livro", "leitor")},
            },
        ),
    ]
