# Generated by Django 4.0.6 on 2024-08-13 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('n_paginas', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='')),
                ('descricao', models.TextField(blank=True)),
                ('moderador', models.BooleanField(default=False)),
                ('id_username', models.CharField(max_length=30, unique=True)),
                ('seguidores', models.ManyToManyField(blank=True, related_name='seguidores_de', to='mainapp.usuario')),
                ('seguindo', models.ManyToManyField(blank=True, related_name='seguidos_por', to='mainapp.usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QL', 'Quero Ler'), ('LN', 'Lendo'), ('LD', 'Lido')], max_length=2)),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.livro')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('pagina_final', models.IntegerField(default=0)),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.livro')),
            ],
        ),
        migrations.CreateModel(
            name='Resenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('texto', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.livro')),
            ],
            options={
                'unique_together': {('livro', 'leitor')},
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('nota', models.IntegerField()),
                ('conteudo', models.TextField()),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usuario')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.livro')),
            ],
            options={
                'unique_together': {('livro', 'leitor')},
            },
        ),
    ]
