# Generated by Django 5.1.3 on 2024-11-12 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name_plural": "Autores",
            },
        ),
        migrations.CreateModel(
            name="Leitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto_perfil", models.ImageField(blank=True, null=True, upload_to="")),
                ("descricao", models.TextField(blank=True)),
                (
                    "seguidores",
                    models.ManyToManyField(
                        blank=True, related_name="seguidores_de", to="mainapp.leitor"
                    ),
                ),
                (
                    "seguindo",
                    models.ManyToManyField(
                        blank=True, related_name="seguidos_por", to="mainapp.leitor"
                    ),
                ),
                (
                    "user_django",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Leitores",
            },
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                (
                    "capa",
                    models.ImageField(
                        blank=True,
                        default="capa/default.jpg",
                        null=True,
                        upload_to="capa/",
                    ),
                ),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("n_paginas", models.IntegerField()),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.autor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resenha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("texto", models.TextField()),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "leitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.leitor"
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.livro"
                    ),
                ),
            ],
            options={
                "unique_together": {("livro", "leitor")},
            },
        ),
    ]
