# Generated by Django 5.1.3 on 2025-01-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitor',
            name='nome',
        ),
    ]
