# Generated by Django 5.1.3 on 2024-12-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leitor',
            old_name='descricao',
            new_name='biografia',
        ),
    ]
