# Generated by Django 5.1.3 on 2025-01-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_leitor_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Comentário'},
        ),
    ]
