# Generated by Django 5.1.3 on 2024-11-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
