# Generated by Django 5.1.3 on 2025-01-28 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_descricao_leitor_biografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='leitor',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='livro',
        ),
        migrations.AddField(
            model_name='comentario',
            name='interacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.interação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='pagina_inicial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interação',
            name='pg_atual',
            field=models.IntegerField(default=0),
        ),
    ]
