# Generated by Django 5.1.3 on 2024-11-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_delete_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
