# Generated by Django 5.1.3 on 2025-02-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_curtida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curtida',
            old_name='usuario',
            new_name='leitor',
        ),
    ]
