# Generated by Django 5.1.1 on 2024-09-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_comentario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, default='capa/default.jpg', null=True, upload_to='capa/'),
        ),
    ]
