# Generated by Django 5.1.3 on 2025-02-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_usuario_curtida_leitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.TextField(),
        ),
    ]
