# Generated by Django 5.1.3 on 2024-12-05 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_autor_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('pagina_final', models.IntegerField(default=0)),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.livro')),
            ],
            options={
                'verbose_name': 'Comentário',
            },
        ),
        migrations.CreateModel(
            name='Interação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QL', 'Quero Ler'), ('LN', 'Lendo'), ('LD', 'Lido')], max_length=2)),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.livro')),
            ],
            options={
                'verbose_name_plural': 'Interações',
                'unique_together': {('livro', 'leitor')},
            },
        ),
    ]
