# Generated by Django 5.1.3 on 2025-03-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_livro_capa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interação',
            new_name='Interacao',
        ),
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Postagem',
        ),
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['-data_hora']},
        ),
        migrations.RenameField(
            model_name='curtida',
            old_name='comentario',
            new_name='postagem',
        ),
    ]
