# Generated by Django 5.1.3 on 2025-05-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_avaliacao'),
        ('mainapp', '0008_leitor_nome'),
    ]

    operations = [
    ]
