# Generated by Django 4.0.6 on 2024-09-02 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_livro_capa_curtida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentário'},
        ),
        migrations.AlterModelOptions(
            name='interage',
            options={'verbose_name_plural': 'Interações'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário'},
        ),
        migrations.AlterUniqueTogether(
            name='interage',
            unique_together={('livro', 'leitor')},
        ),
    ]
