# Generated by Django 4.0.6 on 2024-09-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_autor_options_alter_avaliacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Comentário'},
        ),
    ]
