server {
    listen 80;
    server_name localhost;

    # Onde ficam os arquivos estáticos do build do frontend
    root /usr/share/nginx/html;
    index index.html index.htm;

    # 1. PONTE PARA O BACKEND EXTERNO (EC2 DO BACKEND)
    # Tudo o que o seu front chamar usando '/api/' vai ser jogado para a outra EC2
    location /api {
        # SUBSTITUA 'IP_DA_EC2_DO_BACKEND' pelo IP público ou privado da outra máquina
        # IMPORTANTE: Mantenha a porta que o seu backend roda (ex: 8000, 5000, etc)
        proxy_pass http://3.219.79.120:8000;
        
        # Repassa os cabeçalhos originais para o backend não se perder
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
    }

    # 2. ROTAS DO REACT
    # Se não for uma chamada de API, ele serve as páginas do React Router (evita erro no F5)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Compactação Gzip para performance
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 10240;

    # Tratamento de erro
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
