name: Backend Pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Use python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: change file permissions
        run: |
          cd ./backend/mysite
          chmod +x ./construir_backend.sh
      - name: create python venv with dependencies
        run: |
          cd ./backend/mysite
          sed -i 's/\r$//' ./construir_backend.sh
          ./construir_backend.sh

      - name: run Django system check
        run: |
          cd ./backend/mysite
          source .venv/bin/activate
          python manage.py check

      - name: run migrations
        run: |
          cd ./backend/mysite
          source .venv/bin/activate
          python manage.py migrate

      - name: run backend tests
        run: |
          cd ./backend/mysite
          source .venv/bin/activate
          python manage.py test mainapp.tests
          
      - name: Detect deprecated code
        run: | 
          cd ./backend/mysite
          python -m pip install django-upgrade
          python -m django_upgrade --check --target-version 5.1 $(find . -name "*.py" -not -path "./.venv/*" -not -path "./.venv3/*")

      - name: Execute pylint 
        run: |
          cd ./backend/mysite
          source .venv/bin/activate
          pip install pylint-django
          pylint --load-plugins=pylint_django --disable=all --enable=similarities --min-similarity-lines=2 --ignore-paths=.*/migrations/ --fail-under=10 mainapp mysite

      - name: Execute CPD check
        run: |
          cd ./backend/mysite
          source .venv/bin/activate
          pip install jscpd
          npx jscpd "." --min-lines 50 --reporters json,html --output ./cpd-report --ignore "**/migrations/**,**/venv/**,**/cpd-report/**"